
"""

Django settings for suvios_bpla project.



Generated by 'django-admin startproject' using Django 4.2.1.



For more information on this file, see

https://docs.djangoproject.com/en/4.2/topics/settings/



For the full list of settings and their values, see

https://docs.djangoproject.com/en/4.2/ref/settings/

"""



from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.

BASE_DIR = Path(__file__).resolve().parent.parent





# Quick-start development settings - unsuitable for production

# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/



# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = 'django-insecure-0ij9@0$rh@4!0i!@d*4i(9pih&!1qm+*o!@8)#16d113me+qij'



# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = True



ALLOWED_HOSTS = []





# Application definition



INSTALLED_APPS = [

    'django.contrib.admin',

    'django.contrib.auth',

    'django.contrib.contenttypes',

    'django.contrib.sessions',

    'django.contrib.messages',

    'django.contrib.staticfiles',

    "django_celery_beat",

    'suvios',
    
    'corsheaders',

    'sslserver',

    'django_auth_oidc',

]


AUTHENTICATION_BACKENDS = [

    'django.contrib.auth.backends.ModelBackend',

    'django_auth_oidc.backends.OpenIDConnectBackend',
]




OIDC_RP_CLIENT_ID = '142137900969-fiajikqimj9gnugk3rsqqqj3a0efromr.apps.googleusercontent.com'
OIDC_RP_CLIENT_SECRET = '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'
OIDC_OP_AUTHORIZATION_ENDPOINT = 'https://accounts.google.com/o/oauth2/v2/auth'
OIDC_OP_TOKEN_ENDPOINT = 'https://oauth2.googleapis.com/token'
OIDC_OP_USER_ENDPOINT = 'https://openidconnect.googleapis.com/v1/userinfo'
OIDC_OP_JWKS_ENDPOINT = 'https://www.googleapis.com/oauth2/v3/certs'
OIDC_OP_LOGOUT_ENDPOINT = 'https://accounts.google.com/o/oauth2/revoke'


MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    'corsheaders.middleware.CorsMiddleware',

]



ROOT_URLCONF = 'suvios_bpla.urls'



TEMPLATES = [

    {

        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [BASE_DIR / 'suvios/templates'],

        'APP_DIRS': True,

        'OPTIONS': {

            'context_processors': [

                'django.template.context_processors.debug',

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',

            ],

        },

    },

]



WSGI_APPLICATION = 'suvios_bpla.wsgi.application'





# Database

# https://docs.djangoproject.com/en/4.2/ref/settings/#databases



DATABASES = {

    'default': {

        'ENGINE': 'django.db.backends.sqlite3',

        'NAME': BASE_DIR / 'db.sqlite3',

    }

}





# Password validation

# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_USER_MODEL='suvios.User'

CORS_ORIGIN_ALLOW_ALL = True

LOGIN_URL = '/admin/login/'


AUTH_PASSWORD_VALIDATORS = [

    {

        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',

    },

    {

        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',

    },

    {

        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',

    },

    {

        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',

    },

]





# Internationalization

# https://docs.djangoproject.com/en/4.2/topics/i18n/



LANGUAGE_CODE = 'ru-ru'



TIME_ZONE = 'UTC'



USE_I18N = True



USE_TZ = True





# Static files (CSS, JavaScript, Images)

# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'suvios', 'static')]


